{
 "title": "ThousandEyes Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "TestName",
    "query": {
     "query": "label_values({integration_id=\"$IntegrationId\"},test_name)"
    }
   },
   {
    "name": "AgentName",
    "query": {
     "query": "label_values({integration_id=\"$IntegrationId\"},agent_name)"
    }
   },
   { "name": "IntegrationId", "query": { "query": "label_values(integration_id)" } }
  ]
 },
 "panels": [
  { "title": "Network test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (net_metrics_latency_milliseconds{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (net_metrics_jitter_milliseconds{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Loss",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (net_metrics_loss_percentage{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  { "title": "HTTP test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (http_metrics_throughput_B_per_second{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (http_metrics_response_time_milliseconds{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(http_metrics_availability_percentage{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"}) by(test_name, agent_name)",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  { "title": "Page Load test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Time to complete",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (pageload_metrics_time_milliseconds{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Completion",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pageload_metrics_completion_percentage{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"}) by(test_name, agent_name)",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  }
 ]
}