{
 "title": "ThousandEyes Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "TestName",
    "label": "Test",
    "query": {
     "query": "label_values({integration_id=\"$IntegrationId\"},test_name)"
    }
   },
   {
    "name": "AgentName",
    "label": "Agent",
    "query": {
     "query": "label_values({integration_id=\"$IntegrationId\"},agent_name)"
    }
   },
   { "name": "IntegrationId", "label": "OpenTelemetry Integration ID", "query": { "query": "label_values(integration_id)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Discovered Tests by Test Type",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (test_type) (max by (test_type, test_id) ({__name__!=\"\", test_type!=\"agent-to-server\", test_type!=\"agent-to-agent\"}))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Discovered Tests",
   "type": "table",
   "description": "Click on a test to view in ThousandEyes",
   "gridPos": { "h": 11, "w": 11, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "max by (test_id, test_name, test_type) ({__name__!=\"\", test_name!=\"\", integration_id=\"$IntegrationId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (net_metrics_latency_milliseconds{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (net_metrics_jitter_milliseconds{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Loss",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (net_metrics_loss_percentage{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  { "title": "HTTP test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (http_metrics_throughput_B_per_second{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (http_metrics_response_time_milliseconds{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(http_metrics_availability_percentage{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"}) by(test_name, agent_name)",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  { "title": "Page Load test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Time to complete",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (pageload_metrics_time_milliseconds{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Completion",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pageload_metrics_completion_percentage{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"}) by(test_name, agent_name)",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  { "title": "DNS Server test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Resolution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (dnsserver_metrics_resolution_time_milliseconds{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dnsserver_metrics_availability_percentage{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"}) by(test_name, agent_name)",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  { "title": "FTP test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (ftp_metrics_throughput_B_per_second{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (ftp_metrics_response_time_milliseconds{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ftp_metrics_availability_percentage{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"}) by(test_name, agent_name)",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  { "title": "API test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (api_metrics_time_milliseconds{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Completion",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(api_metrics_completion_percentage{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"}) by(test_name, agent_name)",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Step Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name, step) (api_step_metrics_time_milliseconds{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}}) / Step {{step}}"
    }
   ]
  },
  {
   "title": "Step Completion",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(api_step_metrics_completion_percentage{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"}) by(test_name, agent_name, step)",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}}) / Step {{step}}"
    }
   ]
  },
  { "title": "Transaction test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(test_name, agent_name) (webtransaction_metrics_transaction_time_milliseconds{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Number of errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(test_name, agent_name) (webtransaction_metrics_errors_count{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"})",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  {
   "title": "Completion",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(webtransaction_metrics_completion_percentage{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\", agent_name=~\"$AgentName\"}) by(test_name, agent_name)",
     "legendFormat": "Test ({{test_name}}) - Agent ({{agent_name}})"
    }
   ]
  },
  { "title": "BGP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Path changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(test_name, prefix) (bgp_metrics_path_changes_count{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\"})",
     "legendFormat": "Test ({{test_name}}) ({{prefix}})"
    }
   ]
  },
  {
   "title": "Updates count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(test_name, prefix) (bgp_metrics_updates_count{integration_id=~\"$IntegrationId\", test_name=~\"$TestName\"})",
     "legendFormat": "Test ({{test_name}}) ({{prefix}})"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bgp_metrics_reachability_percentage{integration_id=~\"$IntegrationId\",test_name=~\"$TestName\"}) by(test_name)",
     "legendFormat": "Test ({{test_name}})"
    }
   ]
  }
 ]
}